import:
  # - ~/dotfiles/config/alacritty/catppuccin/catppuccin-latte.yml
  # - ~/dotfiles/config/alacritty/catppuccin/catppuccin-mocha.yml
  # - ~/dotfiles/config/alacritty/catppuccin/catppuccin-frappe.yml
  - ~/dotfiles/config/alacritty/catppuccin/catppuccin-macchiato.yml

font:
  normal:
    family: UbuntuMono Nerd Font
    style: Regular

  bold:
    family: UbuntuMono Nerd Font
    style: Bold

  italic:
    family: UbuntuMono Nerd Font
    style: Italic

  bold_italic:
    family: UbuntuMono Nerd Font
    style: Bold Italic

  size: 12
