[extra]
author = "Estifanos"

[note]
filename = "{{id}}-{{slug title}}"

[group.daily]
paths = ["journal"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

[tool]
fzf-line = "{{style 'blue' rel-path}}{{#each tags}} #{{this}}{{/each}} {{style 'black' body}}"
fzf-preview = "bat -p --color always {-1}"

[alias]
conf = '$EDITOR ~/dotfiles/config/zk/config.toml'
edit = "zk edit --interactive $argv"
daily = 'zk new --no-input "$ZK_NOTEBOOK_DIR/journal"'
n = 'zk new --title "$argv"'
